
import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Platform,
} from 'react-native';
import { router } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useThemeContext } from '@/contexts/ThemeContext';
import { IconSymbol } from '@/components/IconSymbol';
import { StatusBarGradient } from '@/components/ui/StatusBarGradient';

// Placeholder text - replace with your actual terms summary
const TERMS_SUMMARY_TEXT = `Terms Summary

This is a simplified summary of our Terms of Service and Privacy Policy. Please read the full documents for complete details.

What Safe Space Does

Safe Space is a mobile app that provides a supportive environment for you to process your thoughts and feelings through AI-assisted conversations. Think of it as a digital journal with an empathetic AI companion.

Your Account

- You must be at least 13 years old to use Safe Space
- Keep your login credentials secure
- You're responsible for activity on your account
- You can delete your account anytime

Your Privacy

- We collect only the information needed to provide our service
- Your conversations are private and encrypted
- We never sell your personal information
- You can request to see or delete your data anytime

How to Use Safe Space

✓ DO:
- Use the app to reflect on your thoughts and feelings
- Be honest and authentic in your conversations
- Seek professional help when needed
- Respect the service and other users

✗ DON'T:
- Share your account with others
- Use the app for illegal activities
- Attempt to hack or disrupt the service
- Rely on AI responses as professional medical advice

Important Limitations

⚠️ Safe Space is NOT:
- A replacement for professional therapy or counseling
- Emergency mental health support
- Medical, legal, or professional advice

⚠️ In case of emergency:
- Contact emergency services (911 in the US)
- Reach out to a crisis helpline
- Contact a mental health professional

Subscription Plans

- Free Plan: Basic features with limited conversations
- Premium Plan: Unlimited conversations and advanced features
- You can upgrade, downgrade, or cancel anytime
- Refunds are available according to our refund policy

Your Content

- You own the content you create
- We use your content only to provide and improve our service
- You can export or delete your content anytime

AI Responses

- AI responses are generated by machine learning
- They may not always be accurate or appropriate
- Use your judgment when considering AI advice
- The AI learns from conversations but doesn't store personal details

Changes to Terms

- We may update our terms from time to time
- We'll notify you of significant changes
- Continued use means you accept the new terms

Account Deletion

- You can delete your account in Settings
- Deletion is permanent and cannot be undone
- All your data will be removed from our servers

Contact Us

Questions or concerns?
Email: support@safespace.app

Remember: This is just a summary. For complete legal details, please read our full Terms of Service and Privacy Policy.

Your mental health matters. Safe Space is here to support you, but professional help is always available when you need it.`;

export default function TermsSummaryScreen() {
  const { theme } = useThemeContext();

  const handleBack = () => {
    router.back();
  };

  return (
    <LinearGradient
      colors={theme.primaryGradient}
      style={styles.gradientBackground}
      start={{ x: 0, y: 0 }}
      end={{ x: 0, y: 1 }}
    >
      <StatusBarGradient />
      <SafeAreaView style={styles.safeArea} edges={['top', 'bottom']}>
        <View style={styles.container}>
          {/* Header with Back Button */}
          <View style={styles.header}>
            <TouchableOpacity 
              onPress={handleBack} 
              style={styles.backButton}
              activeOpacity={0.7}
            >
              <IconSymbol
                ios_icon_name="chevron.left"
                android_material_icon_name="arrow_back"
                size={24}
                color={theme.buttonText}
              />
            </TouchableOpacity>
            <Text style={[styles.headerTitle, { color: theme.buttonText }]}>
              Terms Summary
            </Text>
            <View style={styles.headerSpacer} />
          </View>

          {/* Scrollable Content */}
          <ScrollView
            style={styles.scrollView}
            contentContainerStyle={styles.scrollContent}
            showsVerticalScrollIndicator={false}
          >
            <View style={[styles.contentCard, { backgroundColor: 'rgba(255, 255, 255, 0.95)' }]}>
              <Text style={[styles.contentText, { color: theme.textPrimary }]}>
                {TERMS_SUMMARY_TEXT}
              </Text>
            </View>
          </ScrollView>
        </View>
      </SafeAreaView>
    </LinearGradient>
  );
}

const styles = StyleSheet.create({
  gradientBackground: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  safeArea: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'android' ? 16 : 8,
    paddingBottom: 16,
  },
  backButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  headerSpacer: {
    width: 40,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  contentCard: {
    borderRadius: 16,
    padding: 24,
    boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.1)',
    elevation: 3,
  },
  contentText: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.2,
  },
});
