
import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Platform,
} from 'react-native';
import { router } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useThemeContext } from '@/contexts/ThemeContext';
import { IconSymbol } from '@/components/IconSymbol';
import { StatusBarGradient } from '@/components/ui/StatusBarGradient';

// Placeholder text - replace with your actual terms of service
const TERMS_OF_SERVICE_TEXT = `Terms of Service & Use

Last Updated: [Date]

Welcome to Safe Space. Please read these Terms of Service carefully before using our application.

1. Acceptance of Terms

By accessing or using Safe Space, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using this application.

2. Description of Service

Safe Space is a mobile application designed to provide a supportive environment for users to process their thoughts and feelings through AI-assisted conversations. The service is provided "as is" and "as available."

3. User Accounts

3.1 Registration
- You must provide accurate and complete information when creating an account
- You are responsible for maintaining the confidentiality of your account credentials
- You must be at least 13 years old to use this service

3.2 Account Security
- You are responsible for all activities that occur under your account
- Notify us immediately of any unauthorized use of your account
- We reserve the right to suspend or terminate accounts that violate these terms

4. User Conduct

You agree not to:
- Use the service for any illegal purpose
- Harass, abuse, or harm other users
- Attempt to gain unauthorized access to our systems
- Interfere with the proper functioning of the service
- Upload malicious code or viruses
- Impersonate any person or entity

5. Content and Intellectual Property

5.1 Your Content
- You retain ownership of the content you create
- You grant us a license to use your content to provide and improve our services
- You are responsible for the content you share

5.2 Our Content
- All service content, features, and functionality are owned by Safe Space
- You may not copy, modify, or distribute our content without permission

6. AI-Generated Content

6.1 Nature of AI Responses
- AI responses are generated by machine learning models
- Responses should not be considered professional medical, legal, or therapeutic advice
- We do not guarantee the accuracy or appropriateness of AI responses

6.2 Limitations
- The AI is not a substitute for professional help
- In case of emergency, contact appropriate emergency services
- We encourage seeking professional support when needed

7. Privacy and Data Protection

Your use of Safe Space is also governed by our Privacy Policy. By using the service, you consent to our collection and use of your information as described in the Privacy Policy.

8. Subscription and Payments

8.1 Free and Premium Plans
- We offer both free and premium subscription tiers
- Premium features require a paid subscription
- Prices are subject to change with notice

8.2 Billing
- Subscriptions are billed in advance on a recurring basis
- You can cancel your subscription at any time
- Refunds are provided according to our refund policy

9. Termination

9.1 By You
- You may delete your account at any time through the app settings
- Deletion is permanent and cannot be undone

9.2 By Us
- We reserve the right to suspend or terminate accounts that violate these terms
- We may discontinue the service with reasonable notice

10. Disclaimers and Limitations of Liability

10.1 No Warranties
- The service is provided "as is" without warranties of any kind
- We do not guarantee uninterrupted or error-free service

10.2 Limitation of Liability
- We are not liable for any indirect, incidental, or consequential damages
- Our total liability is limited to the amount you paid for the service

11. Indemnification

You agree to indemnify and hold Safe Space harmless from any claims, damages, or expenses arising from your use of the service or violation of these terms.

12. Changes to Terms

We reserve the right to modify these terms at any time. We will notify users of significant changes. Continued use of the service after changes constitutes acceptance of the new terms.

13. Governing Law

These terms are governed by the laws of [Jurisdiction], without regard to conflict of law principles.

14. Dispute Resolution

Any disputes arising from these terms or your use of the service will be resolved through binding arbitration, except where prohibited by law.

15. Severability

If any provision of these terms is found to be unenforceable, the remaining provisions will continue in full force and effect.

16. Contact Information

For questions about these Terms of Service, please contact us at:
Email: support@safespace.app

17. Entire Agreement

These Terms of Service, together with our Privacy Policy, constitute the entire agreement between you and Safe Space regarding the use of the service.

By using Safe Space, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.`;

export default function TermsOfServiceScreen() {
  const { theme } = useThemeContext();

  const handleBack = () => {
    router.back();
  };

  return (
    <LinearGradient
      colors={theme.primaryGradient}
      style={styles.gradientBackground}
      start={{ x: 0, y: 0 }}
      end={{ x: 0, y: 1 }}
    >
      <StatusBarGradient />
      <SafeAreaView style={styles.safeArea} edges={['top', 'bottom']}>
        <View style={styles.container}>
          {/* Header with Back Button */}
          <View style={styles.header}>
            <TouchableOpacity 
              onPress={handleBack} 
              style={styles.backButton}
              activeOpacity={0.7}
            >
              <IconSymbol
                ios_icon_name="chevron.left"
                android_material_icon_name="arrow_back"
                size={24}
                color={theme.buttonText}
              />
            </TouchableOpacity>
            <Text style={[styles.headerTitle, { color: theme.buttonText }]}>
              Terms of Service
            </Text>
            <View style={styles.headerSpacer} />
          </View>

          {/* Scrollable Content */}
          <ScrollView
            style={styles.scrollView}
            contentContainerStyle={styles.scrollContent}
            showsVerticalScrollIndicator={false}
          >
            <View style={[styles.contentCard, { backgroundColor: 'rgba(255, 255, 255, 0.95)' }]}>
              <Text style={[styles.contentText, { color: theme.textPrimary }]}>
                {TERMS_OF_SERVICE_TEXT}
              </Text>
            </View>
          </ScrollView>
        </View>
      </SafeAreaView>
    </LinearGradient>
  );
}

const styles = StyleSheet.create({
  gradientBackground: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  safeArea: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'android' ? 16 : 8,
    paddingBottom: 16,
  },
  backButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  headerSpacer: {
    width: 40,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  contentCard: {
    borderRadius: 16,
    padding: 24,
    boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.1)',
    elevation: 3,
  },
  contentText: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.2,
  },
});
